server.port=${PORT:8080}

spring.datasource.url= jdbc:postgresql://ep-bold-glade-ad3ysfx9-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_mfz1sE7RvbWt&sslmode=require&channelBinding=require
spring.datasource.username= neondb_owner
spring.datasource.password= npg_mfz1sE7RvbWt
spring.jpa.hibernate.ddl-auto=update
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
